# Pixel_style: 
#   path: "D:/Study Files/model/sdxl-unstable-diffusers-y"
#   single_files: true    ### if true, is a civitai model
#   use_safetensors: true
#   type: "sdxl"

# # 备选的标准SD模型（如果SDXL有问题）
# Pixel_style_sd: 
#   path: "runwayml/stable-diffusion-v1-5"
#   single_files: false
#   use_safetensors: true
#   type: "sd"

Unstable:
  path: "D:/Study Files/model/sdxl-unstable-diffusers-y"
  single_files: false
  use_safetensors: false
  type: "sdxl"


Tinystable:
  path: "D:/Study Files/model/tiny-stable-diffusion-torch"
  single_files: false
  use_safetensors: false
  type: "sd"