Pixel_style: 
  path: "/home/henry/workspace/model_checkpoint/pixel_style_sdxl/192.safetensors"
  single_files: true   ### if true, is a civitai model
  use_safetensors: true
  type: "sdxl"

# 备选的标准SD模型（如果SDXL有问题）
Pixel_style_sd: 
  path: "runwayml/stable-diffusion-v1-5"
  single_files: false
  use_safetensors: true
  type: "sd"

Unstable:
  path: "/home/henry/workspace/model_checkpoint/unstable_sdxl"
  single_files: false
  use_safetensors: false
  type: "sdxl"