Pixel_style: 
  path: "/home/henry/workspace/model_checkpoint/pixel_style_sdxl/192.safetensors"
  single_files: false   ### if true, is a civitai model
  use_safetensors: true
  type: "sdxl"


Unstable:
  path: "/home/henry/workspace/model_checkpoint/unstable_sdxl"
  single_files: false
  use_safetensors: false
  type: "sdxl"